// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_baudrate(lv_event_t * e);
lv_obj_t * ui_baudrate;
void ui_event_SwitchStartStop(lv_event_t * e);
lv_obj_t * ui_SwitchStartStop;
void ui_event_edevice1(lv_event_t * e);
lv_obj_t * ui_edevice1;
void ui_event_edevice2(lv_event_t * e);
lv_obj_t * ui_edevice2;
lv_obj_t * ui_Spinner;
lv_obj_t * ui_Container1;
lv_obj_t * log_spangroup;
lv_obj_t * log_label;
void ui_event_SwitchHEX(lv_event_t * e);
lv_obj_t * ui_SwitchHEX;
void ui_event_SwitchAscii(lv_event_t * e);
lv_obj_t * ui_SwitchAscii;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label4;

// CUSTOM VARIABLES
lv_obj_t * uic_baudrate;
lv_obj_t * uic_SwitchStartStop;
lv_obj_t * uic_edevice1;
lv_obj_t * uic_edevice2;
lv_obj_t * uic_Spinner;
lv_obj_t * uic_SwitchHEX;
lv_obj_t * uic_SwitchAscii;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_baudrate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_baudrate(e);
    }
}

void ui_event_SwitchStartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        start_stop(e);
    }
}

void ui_event_edevice1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        dev1_check(e);
    }
}

void ui_event_edevice2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        dev2_check(e);
    }
}

void ui_event_SwitchHEX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        sw_hexad(e);
    }
}

void ui_event_SwitchAscii(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        sw_ascii(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
