// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#ifndef _ELEC_TOOLBOX_SL_UI_H
#define _ELEC_TOOLBOX_SL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


// SCREEN: ui_AppMain
void ui_AppMain_screen_init(void);
extern lv_obj_t * ui_AppMain;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

// SCREEN: ui_AppUART
void add_colored_log(const char* timestamp, uint32_t timestamp_color_hex,
    const char* hexa,      uint32_t hexa_color_hex,
    const char* message,   uint32_t message_color_hex);
    
void ui_AppUART_screen_init(void);
void ui_event_AppUART(lv_event_t * e);
extern lv_obj_t * ui_AppUART;
void ui_event_baudrate(lv_event_t * e);
extern lv_obj_t * ui_baudrate;
void ui_event_SwitchStartStop(lv_event_t * e);
extern lv_obj_t * ui_SwitchStartStop;
void ui_event_edevice1(lv_event_t * e);
extern lv_obj_t * ui_edevice1;
void ui_event_edevice2(lv_event_t * e);
extern lv_obj_t * ui_edevice2;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * log_spangroup;
extern lv_obj_t * log_label;
void ui_event_SwitchHEX(lv_event_t * e);
extern lv_obj_t * ui_SwitchHEX;
void ui_event_SwitchAscii(lv_event_t * e);
extern lv_obj_t * ui_SwitchAscii;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;

// CUSTOM VARIABLES
extern lv_obj_t * uic_baudrate;
extern lv_obj_t * uic_SwitchStartStop;
extern lv_obj_t * uic_edevice1;
extern lv_obj_t * uic_edevice2;
extern lv_obj_t * uic_Spinner;
extern lv_obj_t * uic_SwitchHEX;
extern lv_obj_t * uic_SwitchAscii;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
