// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void change_baudrate(lv_event_t * e);
void start_stop(lv_event_t * e);
void dev1_check(lv_event_t * e);
void dev2_check(lv_event_t * e);
void sw_hexad(lv_event_t * e);
void sw_ascii(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
