// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#include "ui.h"
#include "../uart_fnc.h"
#include "../settings.h"
#include <stdlib.h>


long get_selected_baudrate()
{
	char selected[16];
	lv_dropdown_get_selected_str(uic_baudrate, selected, sizeof(selected));

	serial_prt(selected);

	return atol(selected);
}

void change_baudrate(lv_event_t * e)
{
	long baudrate = get_selected_baudrate();

	if (baudrate < 0 || baudrate > 115200) {
		return;
	}

	serial_stop();
	serial_start(baudrate);
}

void start_stop(lv_event_t * e)
{
	lv_obj_t * obj = lv_event_get_target(e);

	// Start reading from the serial port
	if (lv_obj_has_state(obj, LV_STATE_CHECKED)) {
		long baudrate = get_selected_baudrate();

		if (baudrate < 0 || baudrate > 115200) {
			return;
		}

		serial_stop();
		serial_start(baudrate);

	// Stop reading from the serial port
	} else {
		serial_stop();
	}
}

void dev1_check(lv_event_t * e)
{
	set_device(1, lv_obj_has_state(uic_edevice1, LV_STATE_CHECKED));
}

void dev2_check(lv_event_t * e)
{
	set_device(2, lv_obj_has_state(uic_edevice2, LV_STATE_CHECKED));
}

// void sw_hexad(lv_event_t * e)
// {
// 	set_output_hexa(lv_obj_has_state(uic_SetHexa, LV_STATE_CHECKED));
// }

// void sw_ascii(lv_event_t * e)
// {
// 	set_output_ascii(lv_obj_has_state(uic_SetAscii, LV_STATE_CHECKED));
// }

void UartSendData(lv_event_t * e)
{
	// Your code here
}

void changeBrightness(lv_event_t * e)
{
	int value = lv_slider_get_value(uic_setBrightSlide);
	setDisplayBrightness((float)value / 100.0f);
}

void cb_saveUartSettings(lv_event_t * e)
{
	// Save the settings
	
	set_output_ascii(lv_obj_has_state(uic_SetAscii, LV_STATE_CHECKED));
	set_output_hexa(lv_obj_has_state(uic_SetHexa, LV_STATE_CHECKED));
	set_pullups(lv_obj_has_state(uic_SetPullups, LV_STATE_CHECKED));
}

void cb_loadUartSettings(lv_event_t * e)
{
	// Get the actual settings and update the UI

	if (get_output_ascii()) {
		lv_obj_add_state(uic_SetAscii, LV_STATE_CHECKED);
	} else {
		lv_obj_clear_state(uic_SetAscii, LV_STATE_CHECKED);
	}

	if (get_output_hexa()) {
		lv_obj_add_state(uic_SetHexa, LV_STATE_CHECKED);
	} else {
		lv_obj_clear_state(uic_SetHexa, LV_STATE_CHECKED);
	}

	if (get_pullups()) {
		lv_obj_add_state(uic_SetPullups, LV_STATE_CHECKED);
	} else {
		lv_obj_clear_state(uic_SetPullups, LV_STATE_CHECKED);
	}
}
