// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_ORANGE 0
#define UI_THEME_COLOR_COLDEV1 1
#define UI_THEME_COLOR_COLDEV2 2
#define UI_THEME_COLOR_TEXTCOLOR 3
#define UI_THEME_COLOR_HEXA 4
#define UI_THEME_COLOR_COLDEV1BG 5
#define UI_THEME_COLOR_COLDEV2BG 6
#define UI_THEME_COLOR_BACK 7

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Back[1];
extern const ui_theme_variable_t _ui_theme_alpha_Back[1];

extern const ui_theme_variable_t _ui_theme_color_Orange[1];
extern const ui_theme_variable_t _ui_theme_alpha_Orange[1];

extern const ui_theme_variable_t _ui_theme_color_ColDev1[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColDev1[1];

extern const ui_theme_variable_t _ui_theme_color_ColDev1BG[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColDev1BG[1];

extern const ui_theme_variable_t _ui_theme_color_ColDev1BG2[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColDev1BG2[1];

extern const ui_theme_variable_t _ui_theme_color_ColDev2[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColDev2[1];

extern const ui_theme_variable_t _ui_theme_color_ColDev2BG[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColDev2BG[1];

extern const ui_theme_variable_t _ui_theme_color_ColDev2BG2[1];
extern const ui_theme_variable_t _ui_theme_alpha_ColDev2BG2[1];

extern const ui_theme_variable_t _ui_theme_color_TextColor[1];
extern const ui_theme_variable_t _ui_theme_alpha_TextColor[1];

extern const ui_theme_variable_t _ui_theme_color_hexa[1];
extern const ui_theme_variable_t _ui_theme_alpha_hexa[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
