// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#include "../ui.h"

void ui_AppSettings_screen_init(void)
{
    ui_AppSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AppSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_setBrightSlide = lv_slider_create(ui_AppSettings);
    lv_slider_set_range(ui_setBrightSlide, 10, 100);
    lv_slider_set_value(ui_setBrightSlide, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_setBrightSlide) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_setBrightSlide, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_setBrightSlide, 422);
    lv_obj_set_height(ui_setBrightSlide, 13);
    lv_obj_set_x(ui_setBrightSlide, 40);
    lv_obj_set_y(ui_setBrightSlide, -200);
    lv_obj_set_align(ui_setBrightSlide, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_setBrightSlide, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_setBrightSlide, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_object_set_themeable_style_property(ui_setBrightSlide, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_setBrightSlide, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_setBrightSlide, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_setBrightSlide,
                                                                                                     lv_obj_get_style_pad_right(ui_setBrightSlide, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label1 = lv_label_create(ui_AppSettings);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -270);
    lv_obj_set_y(ui_Label1, -200);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Brightness");

    ui_setBrightLbl = lv_label_create(ui_AppSettings);
    lv_obj_set_width(ui_setBrightLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setBrightLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setBrightLbl, 290);
    lv_obj_set_y(ui_setBrightLbl, -200);
    lv_obj_set_align(ui_setBrightLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setBrightLbl, "100 %");

    ui_Container5 = lv_obj_create(ui_AppSettings);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 800);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_align(ui_Container5, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goBackMainSettings = lv_button_create(ui_AppSettings);
    lv_obj_set_width(ui_goBackMainSettings, 150);
    lv_obj_set_height(ui_goBackMainSettings, 36);
    lv_obj_set_x(ui_goBackMainSettings, 0);
    lv_obj_set_y(ui_goBackMainSettings, 215);
    lv_obj_set_align(ui_goBackMainSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goBackMainSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_goBackMainSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_goBackMainSettings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_goBackMainSettings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_Label3 = lv_label_create(ui_goBackMainSettings);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "BACK");

    lv_obj_add_event_cb(ui_setBrightSlide, ui_event_setBrightSlide, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goBackMainSettings, ui_event_goBackMainSettings, LV_EVENT_ALL, NULL);
    uic_setBrightSlide = ui_setBrightSlide;
    uic_setBrightLbl = ui_setBrightLbl;

}
