// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ELEC_TOOLBOX_SL

#include "../ui.h"

void ui_AppUARTsettings_screen_init(void)
{
    ui_AppUARTsettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AppUARTsettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_AppUARTsettings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Back);
    ui_object_set_themeable_style_property(ui_AppUARTsettings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Back);

    ui_UartSettingsTop = lv_obj_create(ui_AppUARTsettings);
    lv_obj_remove_style_all(ui_UartSettingsTop);
    lv_obj_set_width(ui_UartSettingsTop, 800);
    lv_obj_set_height(ui_UartSettingsTop, 44);
    lv_obj_set_align(ui_UartSettingsTop, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_UartSettingsTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UartSettingsTop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UartSettingsTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_UartSettingsTop);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "UART settings");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UartSettingsBottom = lv_obj_create(ui_AppUARTsettings);
    lv_obj_remove_style_all(ui_UartSettingsBottom);
    lv_obj_set_width(ui_UartSettingsBottom, 800);
    lv_obj_set_height(ui_UartSettingsBottom, 50);
    lv_obj_set_align(ui_UartSettingsBottom, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_UartSettingsBottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UartSettingsBottom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UartSettingsBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goBackUartCancel = lv_button_create(ui_UartSettingsBottom);
    lv_obj_set_width(ui_goBackUartCancel, 150);
    lv_obj_set_height(ui_goBackUartCancel, 36);
    lv_obj_set_x(ui_goBackUartCancel, -100);
    lv_obj_set_y(ui_goBackUartCancel, 0);
    lv_obj_set_align(ui_goBackUartCancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goBackUartCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_goBackUartCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goBackUartCancel, lv_color_hex(0xFF5900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goBackUartCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_goBackUartCancel);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "CANCEL");

    ui_goBackUartSave = lv_button_create(ui_UartSettingsBottom);
    lv_obj_set_width(ui_goBackUartSave, 150);
    lv_obj_set_height(ui_goBackUartSave, 36);
    lv_obj_set_x(ui_goBackUartSave, 100);
    lv_obj_set_y(ui_goBackUartSave, 0);
    lv_obj_set_align(ui_goBackUartSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goBackUartSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_goBackUartSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_goBackUartSave, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_goBackUartSave, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_Label10 = lv_label_create(ui_goBackUartSave);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SAVE");

    ui_Container4 = lv_obj_create(ui_AppUARTsettings);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 760);
    lv_obj_set_height(ui_Container4, 60);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -145);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Orange);
    lv_obj_set_style_border_width(ui_Container4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetAscii2 = lv_checkbox_create(ui_Container4);
    lv_checkbox_set_text(ui_SetAscii2, "Ascii ");
    lv_obj_set_width(ui_SetAscii2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetAscii2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetAscii2, 20);
    lv_obj_set_y(ui_SetAscii2, 2);
    lv_obj_set_align(ui_SetAscii2, LV_ALIGN_LEFT_MID);
    lv_obj_add_state(ui_SetAscii2, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_SetAscii2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_SetAscii2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_SetAscii2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_SetAscii2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Orange);
    ui_object_set_themeable_style_property(ui_SetAscii2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_SetAscii2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_SetHexa2 = lv_checkbox_create(ui_Container4);
    lv_checkbox_set_text(ui_SetHexa2, "HEX  ");
    lv_obj_set_width(ui_SetHexa2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetHexa2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_SetHexa2, 130);
    lv_obj_set_y(ui_SetHexa2, 2);
    lv_obj_set_align(ui_SetHexa2, LV_ALIGN_LEFT_MID);
    lv_obj_add_state(ui_SetHexa2, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_SetHexa2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_SetHexa2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_SetHexa2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_SetHexa2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Orange);
    ui_object_set_themeable_style_property(ui_SetHexa2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_SetHexa2, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_Label13 = lv_label_create(ui_AppUARTsettings);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 40);
    lv_obj_set_y(ui_Label13, -175);
    lv_obj_set_align(ui_Label13, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label13, " Display Output ");
    lv_obj_set_style_bg_color(ui_Label13, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_AppUARTsettings);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 760);
    lv_obj_set_height(ui_Container6, 60);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, -65);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_Container6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Orange);
    lv_obj_set_style_border_width(ui_Container6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetPullups = lv_checkbox_create(ui_Container6);
    lv_checkbox_set_text(ui_SetPullups, "Enable Pullups");
    lv_obj_set_width(ui_SetPullups, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetPullups, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetPullups, 20);
    lv_obj_set_y(ui_SetPullups, 2);
    lv_obj_set_align(ui_SetPullups, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SetPullups, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_SetPullups, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_SetPullups, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_SetPullups, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Orange);
    ui_object_set_themeable_style_property(ui_SetPullups, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_SetPullups, LV_PART_INDICATOR | LV_STATE_CHECKED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_Label14 = lv_label_create(ui_AppUARTsettings);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 40);
    lv_obj_set_y(ui_Label14, -95);
    lv_obj_set_align(ui_Label14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label14, " Inputs ");
    lv_obj_set_style_bg_color(ui_Label14, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goBackUartCancel, ui_event_goBackUartCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goBackUartSave, ui_event_goBackUartSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AppUARTsettings, ui_event_AppUARTsettings, LV_EVENT_ALL, NULL);
    uic_SetAscii = ui_SetAscii2;
    uic_SetHexa = ui_SetHexa2;
    uic_SetPullups = ui_SetPullups;

}
